### ISSUE TITLE
Twig Language VS Code extension issue

### ISSUE THREAD

**Issue by mblode** [panoply/vscode-shopify-liquid#6]
Hey @panoply, I love what you've done with your extension! Thank you for sending it to me 👍 

I'm wondering if you'd be able to help me with my own Twig Language extensions? Some files get completely deleted and all the text inside the document is gone. Some files on save delete a large amount and leaves internally placed javascript code behind and no trace of any other code. Is there any chance you could help me with this major bug?

https://github.com/mblode/vscode-twig-language-2

```html

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta content="width=device-width, initial-scale=1.0" name="viewport">
        <meta content="ie=edge" http-equiv="X-UA-Compatible">
        <title>Document</title>
    </head>
    <body>
        <script>console.log("Hello")</script>
    </body>
</html>

```

Then when I beautify as HTML it becomes...

```html

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta content="width=device-width, initial-scale=1.0" name="viewport">
        <meta content="ie=edge" http-equiv="X-UA-Compatible">
        <title>Document</title>
    </head>
    <body>
        <script>console.log("Hello")</script>
    </body>
</html>

```

But finally, if I run the formatter for a second time, the contents of the beautify become...

```js

console.log("Hello")

```

**Comment by panoply** [comment]
Hey @mblode I had a similar issue. The way I fixed this was by adding prettydiff ignore attributes to certain tags upon formatting see [here](https://github.com/panoply/vscode-shopify-liquid/blob/master/src/extension/formatting.js#L13). It was pretty tedious but seemed to work well.

**Comment by panoply** [comment]
So just to follow up on this. 

I might be wrong but this will be due to `<script>` – You need to ignore this element when formatting with PrettyDiff. The same issue occurred for me (if memory calls me correct).  This also happens when PrettyDiff attempts to beautify liquid `{%- comment -%}` tags. It might not be PrettyDiff issue and maybe a VSCode issue, however try the following:

```html
<script data-prettydiff-ignore>
   console.log("Hello")
</script>
```

This will tell PrettyDiff to skip formatting the element (logically) and will be able to diagnose if the `<script>` tag is the core issue here. By default my extension ignores `<script>` tag beautification and the reason for this was due to the disappearing issue, but don't hold me to that because when I wrote this extension I was doing a ton of coke.

In terms of getting you extension to automatically apply the `data-prettydiff-ignore` attribute you can use the solution I come up with or manually apply the ignore tag to elements.

**Comment by mblode** [comment]
@panoply Thank you for your help with this issue! I've incorporated a bunch of your pattern code into my extension and it has officially fixed the issue ❤️ 👍

**Comment by panoply** [comment]
@mblode Awesome news! Glad my code was able to help you. If you advance your extension further where It could help this extension too (given that Twig and Liquid are fairly similar) please don't hesitate to reach out.

**Comment by mblode** [comment]
After a year, my extension has finally gotten to a place where I'm comfortable using it automatically on my code 👌 PrettyDiff 3 is far superior to PrettyDiff 2 and now that we've fixed this bug, its formatting without any issues... whoop whoop!!
